import React from "react";
import {AbsoluteFill,Img,Sequence,interpolate,useCurrentFrame} from "remotion";
import {A} from "./config";

const Text=({children,size=72,dark=false}:{children:React.ReactNode;size?:number;dark?:boolean})=>{
 const f=useCurrentFrame(); const p=interpolate(f,[0,15],[0,1],{extrapolateRight:"clamp"});
 return <div style={{fontFamily:A.font,fontSize:size,fontWeight:600,letterSpacing:"-.045em",lineHeight:.98,color:dark?A.black:A.white,opacity:p,transform:`translateY(${(1-p)*28}px)`}}>{children}</div>;
};
const Shot=({src,width,left,top}:{src:string;width:number;left:number;top:number})=>{
 const f=useCurrentFrame(); const s=interpolate(f,[0,90],[.96,1.03],{extrapolateRight:"clamp"});
 return <div style={{position:"absolute",width,left,top,overflow:"hidden",borderRadius:18,boxShadow:"0 40px 100px rgba(0,0,0,.24)",transform:`scale(${s})`}}><Img src={src} style={{display:"block",width:"100%"}}/></div>;
};
const Intro=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:A.black,display:"grid",placeItems:"center"}}><Img src={A.logo} style={{position:"absolute",width:360,opacity:interpolate(f,[0,18,42,58],[0,1,1,0],{extrapolateRight:"clamp"})}}/><div style={{position:"absolute",opacity:interpolate(f,[42,58,75,90],[0,1,1,0],{extrapolateRight:"clamp"})}}><Text size={92}>PHOTOGRAPHY IS A BUSINESS.</Text></div></AbsoluteFill>};
const Position=()=> <AbsoluteFill style={{background:A.white,padding:"120px 110px"}}><div style={{width:180,height:5,background:A.purple}}/><div style={{marginTop:55,fontFamily:A.font,fontSize:28,color:A.purple,fontWeight:600}}>KLIQAT</div><div style={{marginTop:190}}><Text dark size={88}>All-in-one workspace<br/>for photographers.</Text></div></AbsoluteFill>;
const Projects=({prototype=false}:{prototype?:boolean})=><AbsoluteFill style={{background:"#F6F6F6"}}><div style={{position:"absolute",left:110,top:130,zIndex:2}}><Text dark size={68}>Manage every<br/>project.</Text><div style={{marginTop:28,fontFamily:A.font,fontSize:21,color:"#666"}}>One workspace. Less scattered work.</div></div><Shot src={A.projects} width={1450} left={prototype?330:390} top={prototype?280:245}/></AbsoluteFill>;
const Detail=()=> <AbsoluteFill style={{background:"#F7F7F7"}}><Shot src={A.detail} width={1620} left={150} top={165}/><div style={{position:"absolute",left:110,top:100,zIndex:2}}><Text dark size={46}>Anushka &amp; Virat</Text></div></AbsoluteFill>;
const Gallery=()=> <AbsoluteFill style={{background:A.black}}><Shot src={A.gallery} width={1540} left={310} top={170}/><div style={{position:"absolute",left:110,top:300,zIndex:2}}><Text size={64}>From selection<br/>to delivery.</Text></div></AbsoluteFill>;
const Team=()=> <AbsoluteFill style={{background:"#F7F7F7"}}><Shot src={A.assignments} width={1580} left={270} top={210}/><div style={{position:"absolute",left:110,top:140,zIndex:2}}><Text dark size={62}>Keep your<br/>team moving.</Text></div><div style={{position:"absolute",right:110,bottom:85,fontFamily:A.font,fontSize:18,color:A.purple,fontWeight:600}}>ASSIGNED → IN PROGRESS → REVIEW → APPROVED</div></AbsoluteFill>;
const Business=()=>{const items=["Clients.","Projects.","Finance.","Team.","Delivery."];return <AbsoluteFill style={{background:A.white,padding:"105px 110px"}}><div style={{fontFamily:A.font,fontSize:18,fontWeight:600,color:A.purple,letterSpacing:".12em"}}>ONE WORKSPACE</div><div style={{marginTop:145,display:"flex",flexDirection:"column",gap:12}}>{items.map((x,i)=>{const f=useCurrentFrame();const p=interpolate(f,[i*7,i*7+16],[0,1],{extrapolateRight:"clamp"});return <div key={x} style={{fontFamily:A.font,fontSize:92,lineHeight:.94,fontWeight:i===2?600:500,color:i===2?A.purple:A.black,letterSpacing:"-.055em",opacity:p,transform:`translateX(${(1-p)*80}px)`}}>{x}</div>})}</div></AbsoluteFill>};
const Outro=()=> <AbsoluteFill style={{background:A.black,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><Img src={A.logo} style={{width:420}}/><div style={{marginTop:55,width:520,height:4,background:A.purple}}/><div style={{marginTop:40}}><Text size={34}>All-in-one workspace for photographers.</Text></div></AbsoluteFill>;

export const KliqAtFilm=({prototype=false}:{prototype?:boolean})=>prototype?<AbsoluteFill><Sequence from={0} durationInFrames={62}><Intro/></Sequence><Sequence from={52} durationInFrames={38}><Position/></Sequence><Sequence from={82} durationInFrames={68}><Projects prototype/></Sequence></AbsoluteFill>:<AbsoluteFill><Sequence from={0} durationInFrames={60}><Intro/></Sequence><Sequence from={54} durationInFrames={66}><Position/></Sequence><Sequence from={114} durationInFrames={90}><Projects/></Sequence><Sequence from={198} durationInFrames={90}><Detail/></Sequence><Sequence from={282} durationInFrames={90}><Gallery/></Sequence><Sequence from={366} durationInFrames={90}><Team/></Sequence><Sequence from={450} durationInFrames={60}><Business/></Sequence><Sequence from={504} durationInFrames={36}><Outro/></Sequence></AbsoluteFill>;